
#ifndef CONCUDARING_CONSTANTS_H
#define CONCUDARING_CONSTANTS_H

//SHARED MEMORY CONSTS
//TODO No se puede abrir el siguiente archivo
#define FILE_CONCUDARING "concudaring.tmp"
#define KEY_MEMORY 'm'

//CREATOR OF cards
#define CANTIDAD_CARTAS 48

//SEMAPHORE CONSTS

#define KEY_SEM_WAIT_FOR_A_CARD 'a'
#define KEY_SEM_END_OF_TURN_GATHERING 'b'
#define KEY_SEM_THERE_IS_CARD 't'
#define KEY_SEM_READ_LOSER 'r'
#define KEY_SEM_WRITE_LOSER 'w'
#define KEY_MEM_NO_ONE_WON 'c'
#define KEY_SEM_WRITE_NUMBER_OF_CARDS 'f'
#define KEY_SEM_JUDE_CONDITION 'z'


//SHARED MEMORY CONSTS
#define KEY_SHME_JUDGE 'j'
#define KEY_SHME_TABLE_NUMBER_PLAYER_PUT_HAND 'e'
#define KEY_SHME_TABLE_I 'g'
#define KEY_SHME_TABLE_ID_HAND 'h'
#define KEY_SHME_TABLE_CARDS 'i'
#define KEY_SHME_JUDGE_CONDITION 'k'
#endif //CONCUDARING_CONSTANTS_H
